lifesafe4u_user_security_login:
    pattern: /login
    defaults: { _controller: LifeSafe4UUserBundle:Security:login }

lifesafe4u_user_security_check:
    pattern: /login_check
    defaults: { _controller:LifeSafe4UeUserBundle:Security:check }

lifesafe4u_user_security_logout:
    pattern: /logout
    defaults: { _controllerLifeSafe4UreUserBundle:Security:logout }
