security:
    encoders:
        LifeSafe4U\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_COMPANY_ADMIN: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_COMPANY_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        main:
#            id: lifesafe4u_user.user_provider
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

#        main:
#            provider: main
#            pattern:   ^/
#            logout:
#                path: /logout
#                target: /
#            form_login:
#                username_parameter: login[email]
#                password_parameter: login[password]
#                login_path:  /login
#                default_target_path: /
#            anonymous: true
#            remember_me:
#                key:      %secret%
#                lifetime: 172800
#                path:     /
#                domain:   ~
#                user_provider: main
#            switch_user: { role: ROLE_ADMIN }

        default:
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
